import Link from 'next/link';
import { requireAdmin } from '../../lib/selfhost-auth';
import { db, ensureSelfHostedSchema } from '../../lib/selfhost-db';
export const dynamic='force-dynamic';
export default async function AdminPage({searchParams}:{searchParams:Promise<{created?:string;userError?:string}>}){
  const user=await requireAdmin('/admin');await ensureSelfHostedSchema();const notice=await searchParams;
  const [stats]=await db()<Array<{users:number;projects:number;images:number;creditsSpent:number}>>`SELECT (SELECT count(*)::int FROM app_users) AS users,(SELECT count(*)::int FROM projects) AS projects,(SELECT count(*)::int FROM generated_assets) AS images,(SELECT coalesce(sum(credit_cost),0)::int FROM generated_assets) AS "creditsSpent"`;
  const users=await db()<Array<{id:string;name:string;email:string;role:string;credits:number;projects:number;images:number}>>`SELECT u.id,u.name,u.email,u.role,u.credits,count(DISTINCT p.id)::int AS projects,count(DISTINCT a.id)::int AS images FROM app_users u LEFT JOIN projects p ON p.owner_id=u.id LEFT JOIN generated_assets a ON a.owner_id=u.id GROUP BY u.id ORDER BY u.created_at DESC LIMIT 50`;
  const configured=[['GPT Image 2',Boolean(process.env.OPENAI_API_KEY),process.env.OPENAI_IMAGE_MODEL||'gpt-image-2'],['Nano Banana 2',Boolean(process.env.GEMINI_API_KEY),process.env.GEMINI_IMAGE_MODEL||'gemini-3.1-flash-image']];
  return <main className="admin-shell"><header className="admin-header"><div className="brand"><span className="brand-mark">N</span><span>NovaCanvas Admin</span></div><span>{user.email} · <Link href="/">返回工作台</Link></span></header><section className="admin-content"><h1>运营管理后台</h1><p>以下全部为当前服务器的真实数据。</p>{notice.created&&<div className="admin-notice success">已创建账号：{notice.created}</div>}{notice.userError&&<div className="admin-notice error">{notice.userError}</div>}<div className="stat-grid">{[['注册账号',stats?.users??0],['Listing 项目',stats?.projects??0],['生成素材',stats?.images??0],['累计消耗',`${stats?.creditsSpent??0} 点`]].map(x=><article className="stat-card" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>实时数据库</small></article>)}</div><section className="admin-panel create-user-panel"><h2>创建运营账号</h2><p>给每位运营创建独立账号，无需共享管理员密码。</p><form action="/api/admin/users" method="post"><label>姓名<input name="name" required placeholder="例如：亚马逊运营 A"/></label><label>公司邮箱<input name="email" type="email" required placeholder="name@company.com"/></label><label>初始密码<input name="password" type="password" minLength={10} required placeholder="至少 10 位"/></label><label>角色<select name="role"><option value="member">普通成员</option><option value="admin">管理员</option></select></label><button type="submit">创建账号</button></form></section><section className="admin-panel"><h2>账号与用量</h2><div className="admin-list"><div><span>账号</span><span>角色 / 算力</span><span>项目</span><span>素材</span></div>{users.map(row=><div key={row.id}><span><b>{row.name}</b><small>{row.email}</small></span><span><em>{row.role}</em> · {row.credits} 点</span><span>{row.projects}</span><span>{row.images}</span></div>)}</div></section><section className="admin-panel"><h2>作图引擎</h2><div className="admin-list"><div><span>引擎</span><span>状态</span><span>模型</span><span>配置位置</span></div>{configured.map(row=><div key={String(row[0])}><span>{String(row[0])}</span><span><em className={row[1]?'':'offline'}>{row[1]?'已配置':'未配置'}</em></span><span>{String(row[2])}</span><span>服务器 .env</span></div>)}</div></section></section></main>;
}
