import Link from 'next/link';
import { requireAppUser } from '../../lib/selfhost-auth';
import { db, ensureSelfHostedSchema } from '../../lib/selfhost-db';
export const dynamic='force-dynamic';
export default async function AccountPage(){
  const user=await requireAppUser('/account');await ensureSelfHostedSchema();
  const [stats]=await db()<Array<{projects:number;images:number;spent:number}>>`SELECT (SELECT count(*)::int FROM projects p WHERE owner_id=${user.id} AND EXISTS (SELECT 1 FROM generated_assets a WHERE a.project_id=p.id)) AS projects,(SELECT count(*)::int FROM generated_assets WHERE owner_id=${user.id}) AS images,(SELECT coalesce(sum(credit_cost),0)::int FROM generated_assets WHERE owner_id=${user.id}) AS spent`;
  const initials=(user.name||user.email).slice(0,2).toUpperCase();const role=user.role==='owner'?'所有者':user.role==='admin'?'管理员':'成员';
  return <main className="auth-page"><section className="account-shell"><aside className="account-nav"><div className="brand"><span className="brand-mark">N</span><span>NovaCanvas</span></div><Link className="active" href="/account">◎ 账号概览</Link><Link href="/projects">▦ Listing 项目</Link><Link href="/workbench">✦ 套图工作台</Link>{(user.role==='owner'||user.role==='admin')&&<Link href="/admin">⌘ 管理后台</Link>}<form action="/api/auth/logout" method="post"><button className="account-signout" type="submit">↗ 退出登录</button></form></aside><section className="account-main"><h1>账号与工作空间</h1><p>这里显示当前账号的真实项目、素材与算力数据。</p><div className="profile-banner"><i>{initials}</i><span><b>{user.name}</b><small>{user.email}</small></span><em>{role}</em></div><div className="account-grid"><article className="account-card"><h2>工作概览</h2><dl><div><dt>Listing 项目</dt><dd>{stats?.projects??0} 个</dd></div><div><dt>已生成素材</dt><dd>{stats?.images??0} 张</dd></div><div><dt>累计消耗</dt><dd>{stats?.spent??0} 点</dd></div><div><dt>当前角色</dt><dd>{role}</dd></div></dl></article><article className="account-card"><h2>可用算力</h2><div className="plan"><div><strong>{user.credits}</strong><p>当前剩余点数<br/>Nano Banana 6 点 / GPT Image 10 点</p></div><Link className="dark-button" href="/workbench">开始作图</Link></div></article><article className="account-card"><h2>安全与数据</h2><dl><div><dt>登录方式</dt><dd>公司独立账号</dd></div><div><dt>会话保护</dt><dd>HttpOnly Cookie</dd></div><div><dt>素材存储</dt><dd>服务器私有卷</dd></div><div><dt>数据隔离</dt><dd>按账号授权</dd></div></dl></article><article className="account-card"><h2>快捷入口</h2><div className="quick-links"><Link href="/projects">查看全部项目</Link><Link href="/compliance">检查图片合规</Link><Link href="/a-plus">制作 A+ 内容</Link></div></article></div><Link className="back-link" href="/workbench">← 返回 Amazon 套图工作台</Link></section></section></main>;
}
